services:
  - type: web
    name: tahoservice
    runtime: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: TahoService
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: tahoservice-db
          property: connectionString
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: TRUSTED_PROXIES
        value: "*"

databases:
  - name: tahoservice-db
    plan: free
