name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping TahoService
        run: curl -s https://tahoservice.onrender.com > /dev/null
